### PR TITLE
removing protocol from url on init

### PR DESCRIPTION
**Pull request by mhkarimi1383**
this will resolve problem when user set `limoo_url` with http or https (exception on connot resolve name `https:443`)

### CODE REVIEW

**Comment by soroosh-chabi** [comment]
Interestingly, even I made the mistake of including the scheme in the `limoo_url` argument a few times; so thanks for fixing it. However I think it would be better if we didn't just cut the scheme out of `limoo_url` because if the scheme is HTTP and the `secure` argument is left to its default of `True`, we'll likely get unexpected results. One solution that comes to my mind is to change the default for `secure` to `None` and use HTTPS if neither the scheme nor `secure` are specified. Alternatively, if the scheme is included in `limoo_url` you could throw an exception with a descriptive message.

**Comment by mhkarimi1383** [comment]
Okay 👌 I will make it better and apply you suggestion

**Comment by mhkarimi1383** [comment]
I have found another way for that :)

**Comment by soroosh-chabi** [comment]
It was a nice refactoring you did but logically, it is pretty much the same as the first commit and doesn't really address my concern. I'm worried about potential inconsistencies resulting from the presence of a scheme in `limoo_url` argument and the value (default or otherwise) of `secure` argument.

**Comment by mhkarimi1383** [comment]
I tested with multiple arguments and it worked

**Comment by soroosh-chabi** [comment]
What I meant is that semantically, the two arguments can be inconsistent and that situation needs to be handled properly. For instance say `limoo_url` is set to `'https://web.limoo.im'` and `secure` is set to `False`. The way it's implemented now, the HTTPS scheme will be wiped from `limoo_url` and since `secure` is set to `False`, the driver will try to connect using insecure HTTP and WS protocols which is certainly confusing to the user. I have two proposals on how to solve this:
1. Set the default value for `secure` to `None`. Also check for possible inconsistencies between `limoo_url` and `secure` and if any has been encountered, an exception must be thrown.
2. Remove the `secure` argument completely and make sure that either a "http" or "https" scheme has been specified in `limoo_url`.
Since I estimate that people will be providing a scheme, I favor the second solution as it is just simpler to understand and work with.

**Comment by mhkarimi1383** [comment]
checking if schema is available and set secure by that :)

**Comment by soroosh-chabi** [comment]
@mhkarimi1383 What do you think of this alternative? It catches the mistake and gives a helpful error message instead of the old cryptic one, all the while keeping the code as simple as before and avoiding potential inconsistencies between `limoo_url` and `secure`. I should note that the reason I insist on not letting a Scheme into the URL is because the driver uses more than just one protocol (HTTP or HTTPS) to communicate with the Limoo server: it also needs WebSocket. So by prohibiting the Scheme, we diminish chances of misconceptions about the communication protocol(s) used.

**Comment by mhkarimi1383** [comment]
Now That's Better...

**Pull request merged**
